## Below 2 functions are used to calculate (and cache) the inverse of a Matrix.

## First function makeCacheMatrix creates a list of 3 functions for getting 
## the original matrix, setting the inverse matrix, and getting the inverse matrix.

makeCacheMatrix <- function(x = matrix()) {
        i <- NULL
        get <- function() x
        setIM <- function(IM) i <<- IM
        getIM <- function() i
        list(get = get, setIM = setIM, getIM = getIM)
}


## 2nd Function cacheSolve is passed as an argument the list generated by 1st function over
## a valid matrix. For example x = make_matrix, where make_matrix <- makeCacheMatrix(valid_matix).
## The cacheSolve function checks to see if the inverse matrix (denoted by i) has already been defined.
## If defined it returns the inverse matrix from memory (rather than recalculing it).
## However if not defined the original matrix is retrieved and 'solve' function carried out on it
## to calculate and return the inverse matrix

cacheSolve <- function(x, ...) {
        i<- x$getIM()
        if(!is.null(i)) {
                message("getting cached inverted matrix")
                return(i)
        }
        matrix_data <- x$get()
        i <- solve(matrix_data, ...)
        x$setIM(i)
        ## Return a matrix that is the inverse of 'x'
        i
}
